{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "devopsschool.fullname" . }}
  labels:
    {{- include "devopsschool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "devopsschool.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end -}}
