apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsschool.fullname" . }}
  labels:
    {{- include "devopsschool.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "devopsschool.selectorLabels" . | nindent 4 }}

{{- if and (eq .Values.service.type "ClusterIP") .Values.service.headless }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsschool.fullname" . }}-headless
  labels:
    {{- include "devopsschool.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "devopsschool.selectorLabels" . | nindent 4 }}
{{- end }}
