version: '3.9'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    environment:
      TZ: Europe/Moscow
      # GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    logging:
      driver: "json-file"
      options:
        max-size: "50m"


  gitlab-runner:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
